function tauPerformance(d, colorUsers, colorModels, figNum, fontSize)
%TAUPERFORMANCE Draws Thurstonian and Borda performance when there is a
%               ground truth
%   tauPerformance(d, colorSubjects, colorPosterior, figNum, fontSize)

% constants
scaleUsers = 0.9;
scalePosterior = 0.4;
maxTau = d.nuItem*(d.nuItem-1)/2;

% histogram counts
countUser = hist(d.userTau, 0:maxTau);
countUser = scaleUsers*countUser/max(countUser);
countThurstone = hist(d.posteriorTau, 0:maxTau);
countThurstone = scalePosterior*countThurstone/max(countThurstone);

% figure window
figure(figNum); clf; hold on;
set(gcf, ...
    'color'             , 'w'           , ...
    'units'             , 'normalized'  , ...
    'position'          , [.1 .1 .8 .8] , ...
    'paperpositionmode' , 'auto'        );

% axis
set(gca, ...
    'units'      , 'normalized'            , ...
    'position'   , [.2 .2 .6 .5]           , ...
    'ycolor'     , 'none'                  , ...
    'ylim'       , [0 1]                   , ...
    'xlim'       , [-1 maxTau+1]           , ...
    'xtick'      , [0 maxTau]              , ...
    'ticklength' , [.01 0]                 , ...
    'tickdir'    , 'out'                   , ...
    'box'        , 'off'                   , ...
    'fontsize'   , fontSize                , ...
    'layer'      , 'top'                   );

% labels
xlabel('Tau Distance', 'fontsize', fontSize + 2);
text(-1, 0.5, ...
    sprintf('%s\n %d people\n %d items', d.name, d.nuUser, d.nuItem), ...
    'fontsize' , fontSize + 2     , ...
    'vert'     , 'mid'            , ...
    'hor'      , 'right'          );

% subjects
bar(0:maxTau, countUser, ...
    'facecolor', colorUsers , ...
    'edgecolor', 'none'        );

% borda
plot([d.bordaTau d.bordaTau], [0 1], '-', ...
    'linewidth', 4, ...
    'color', 'w');
plot([d.bordaTau d.bordaTau], [0 1], '--', ...
    'linewidth', 2, ...
    'color', colorModels);
text(d.bordaTau, 1, 'Borda', ...
    'rot', 90, ...
    'fontsize', fontSize, ...
    'vert', 'top');

% thurstone
plot([d.thurstoneTau d.thurstoneTau], [0 1], '-', ...
    'linewidth', 4, ...
    'color', 'w');
plot([d.thurstoneTau d.thurstoneTau], [0 1], '--', ...
    'linewidth', 2, ...
    'color', colorModels);
text(d.thurstoneTau, 1, 'Thurstone', ...
    'rot', 90, ...
    'fontsize', fontSize, ...
    'vert', 'bot');
keep = find(countThurstone > 0);
bar(keep-1, countThurstone(keep), 1, ...
    'linewidth', 1.5     , ...
    'facecolor', 'none', ...
    'edgecolor', colorModels );


% inset
insetAX = axes; hold on;
set(insetAX, ...
    'units'      , 'normalized'            , ...
    'position'   , [.6 .475 .2 .325]           , ...
    'xlim'       , [0 max(d.sigma)]                   , ...
    'xtick'      , []                      , ...
    'ylim'       , [0 max(d.userTau)]              , ...
    'ytick'      , []              , ...
    'ticklength' , [.01 0]                 , ...
    'tickdir'    , 'out'                   , ...
    'box'        , 'off'                   , ...
    'fontsize'   , fontSize                , ...
    'layer'      , 'top'                   );

% labels
xlabel('Inferred Expertise', 'fontsize', fontSize);
ylabel('Tau Distance', 'fontsize', fontSize);

% plot
plot(d.sigma, d.userTau, 'o', ...
    'markerfacecolor', 'k', ...
    'markeredgecolor', 'w', ...
    'markersize', 6);

% correlation
tmp = corrcoef(d.sigma, d.userTau);
text(0, max(d.userTau), sprintf(' r = %1.2f', tmp(1, 2)), ...
    'fontsize', fontSize, ...
    'vert', 'top');

